name: build

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build packages
        run: |
          nix build --no-link --print-out-paths \
            .#actuated-cli \
            .#caddy \
            .#mass-deploy \
            .#kubetrim \
            .#hunk \
            .#herdr
